name: Data Preparation Pipeline

on:
  push:
    branches:
      - main
    tags:
      - '*'   
  schedule:
    - cron: "0 20 * * *"
    # 3 - 7 = [ -4 ]
    # karena minus, jadi 24 - 4 = [ 20 ]

jobs:
  data_preparation_job:
    name: Data Preparation Job
    runs-on: ubuntu-latest
    environment: Production

    strategy:
      matrix:
        python-version: [3.11]

    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      DATASET_NAME: indonesia_stocks
      HF_USERNAME: qywok

    steps:
      - name: Set global directory
        run: git config --global --add safe.directory /github/workspace

      - uses: actions/checkout@v3     
        with:
          lfs: true
          persist-credentials: false
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cloning datasets from hugging face
        id: cloning_dataset
        run: git clone https://huggingface.co/datasets/$HF_USERNAME/$DATASET_NAME

      - name: Requirements Install
        id: requirements_install
        run: pip install -r requirements/linux/ubuntu.production.txt

      - name: Get Current Date
        id: get_current_date
        run: |
          full_date=$(date)
          current_date=$(date +%d)
          current_date=$((10#$current_date + 1))
          echo "FULL_DATE=${full_date}" >> $GITHUB_ENV
          echo "CURRENT_DATE=${current_date}" >> $GITHUB_ENV

      - name: Collecting, and Preparing Data
        id: collect_prepare_data
        run: |
          if [ "$CURRENT_DATE" -eq 28 ]; then
            GEN_NEW_DATA="True"
          else
            GEN_NEW_DATA="False"
          fi
          python main.py \
            --gen_new_data=$GEN_NEW_DATA --process=SYNC \
            --ranking_by=HEAD_RANK --ranking_number=50

      - name: ingest to hugging face
        run: |
          cd indonesia_stocks
          git config --local user.email "alfariqyraihan@gmail.com"
          git config --local user.name "qywok"
          git add -A 
          git diff-index --quiet HEAD || git commit -m "[Ingest Date ]: $FULL_DATE"
          git push https://$HF_USERNAME:$HF_TOKEN@huggingface.co/datasets/$HF_USERNAME/$DATASET_NAME main --force


